branches:
  except:
  - develop
  - gh-pages
language: node_js
node_js:
- 6.1.0
cache:
  directories:
  - node_modules
script:
- npm test
- bash ./scripts/deploy-to-gh-pages.sh
env:
  global:
  - secure: i7igtOlHbrveytww8VfR5B2YmfXX/UUhtvE0vufJ4lgOVl4Xn5PrpJXJ5Om6JvMBrgM41ybcCtvpGpQPxdlaMLq5Q+qBntScuXv/igMnLIGEDQz1G8kGB1EfwE7l+hAiI8G1XrTUM/pRCJOkQoTvqOUPvgGXgFIUcU4ZsQlEJk5FRLjr1ep6RtPumIBx4+6qSZhh1XKFTsVI6CcLH9GcH0YhS4G1Nug7If2HVdhYzBOzqLPvItgj8qTO27FDOlFdXbsaZWJcbUtwmStz5lh7lh1Q9H1AF6nW7LnfvXEEVnSE/JaBDHSuJkOpNaiT+4pJDRoY7ksS1e9i/pxPpu8CMJ6qTzwvO7HNzPV/3dObLNO23W2H4OqNlj9VogsB1/sGChsCUGlZOy2BUpWjBrLPdpl7LFDIOjDcha1X6nvRoS7fsmlEs6PU9mDj36LanAhwaJ/zt2/0bveVxcz/9w/dYJ8dRk6sPl/7vJ08utAijyIC5PYfSk8bfgcPdJ/CaxmLp4Q7Iz9lc8vdUV5xkmE5BytkhXKvAoD+U57sIzkofPft0xG5bb2J5erbtO53Fjp17GtZhfWxS1ehdXFB50iIwlXX0OFgXstKQLc4uBpmwW5f/v5+xQH0SU7sgIVZ8cMNopXd6Sviad+X/p/nRDQ1hopHyiVWFcQBKQ1nCvxIIOE=
